# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/face_recognition.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FaceRecApp(object):
    def setupUi(self, FaceRecApp):
        FaceRecApp.setObjectName("FaceRecApp")
        FaceRecApp.resize(886, 653)
        icon = QtGui.QIcon.fromTheme("camera-video")
        FaceRecApp.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(FaceRecApp)
        self.centralwidget.setObjectName("centralwidget")
        self.viewFinderPage = QtWidgets.QWidget(self.centralwidget)
        self.viewFinderPage.setGeometry(QtCore.QRect(20, 60, 661, 501))
        self.viewFinderPage.setAutoFillBackground(False)
        self.viewFinderPage.setObjectName("viewFinderPage")
        self.gridLayout = QtWidgets.QGridLayout(self.viewFinderPage)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.cameraSurface = QtWidgets.QLabel(self.viewFinderPage)
        self.cameraSurface.setMinimumSize(QtCore.QSize(640, 480))
        self.cameraSurface.setMaximumSize(QtCore.QSize(640, 480))
        self.cameraSurface.setFrameShape(QtWidgets.QFrame.Box)
        self.cameraSurface.setText("")
        self.cameraSurface.setObjectName("cameraSurface")
        self.gridLayout.addWidget(self.cameraSurface, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(720, 160, 121, 281))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.startButton = QtWidgets.QPushButton(self.groupBox)
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.pauseButton = QtWidgets.QPushButton(self.groupBox)
        self.pauseButton.setObjectName("pauseButton")
        self.verticalLayout.addWidget(self.pauseButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.stopButton = QtWidgets.QPushButton(self.groupBox)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout.addWidget(self.stopButton)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(690, 80, 181, 27))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.faceRegistrySelect = QtWidgets.QComboBox(self.splitter)
        self.faceRegistrySelect.setObjectName("faceRegistrySelect")
        FaceRecApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FaceRecApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 886, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDevices = QtWidgets.QMenu(self.menubar)
        self.menuDevices.setObjectName("menuDevices")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        FaceRecApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FaceRecApp)
        self.statusbar.setObjectName("statusbar")
        FaceRecApp.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(FaceRecApp)
        self.actionExit.setObjectName("actionExit")
        self.actionStartCamera = QtWidgets.QAction(FaceRecApp)
        self.actionStartCamera.setObjectName("actionStartCamera")
        self.actionStopCamera = QtWidgets.QAction(FaceRecApp)
        self.actionStopCamera.setObjectName("actionStopCamera")
        self.actionRegisterFaces = QtWidgets.QAction(FaceRecApp)
        self.actionRegisterFaces.setObjectName("actionRegisterFaces")
        self.actionViewFaceRegistry = QtWidgets.QAction(FaceRecApp)
        self.actionViewFaceRegistry.setObjectName("actionViewFaceRegistry")
        self.actionAddAlbum = QtWidgets.QAction(FaceRecApp)
        self.actionAddAlbum.setObjectName("actionAddAlbum")
        self.actionDeleteAlbum = QtWidgets.QAction(FaceRecApp)
        self.actionDeleteAlbum.setObjectName("actionDeleteAlbum")
        self.menuFile.addAction(self.actionRegisterFaces)
        self.menuFile.addAction(self.actionAddAlbum)
        self.menuFile.addAction(self.actionDeleteAlbum)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionViewFaceRegistry)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuDevices.menuAction())
        self.label.setBuddy(self.faceRegistrySelect)

        self.retranslateUi(FaceRecApp)
        self.startButton.clicked.connect(FaceRecApp.start)
        self.pauseButton.clicked.connect(FaceRecApp.pause)
        self.stopButton.clicked.connect(FaceRecApp.stop)
        self.actionRegisterFaces.triggered.connect(FaceRecApp.register_faces)
        self.actionAddAlbum.triggered.connect(FaceRecApp.create_registry)
        self.actionViewFaceRegistry.triggered.connect(FaceRecApp.view_registry)
        self.actionExit.triggered.connect(FaceRecApp.close)
        self.actionDeleteAlbum.triggered.connect(FaceRecApp.delete_registry)
        self.faceRegistrySelect.currentIndexChanged['QString'].connect(FaceRecApp.set_current_registry)
        QtCore.QMetaObject.connectSlotsByName(FaceRecApp)

    def retranslateUi(self, FaceRecApp):
        _translate = QtCore.QCoreApplication.translate
        FaceRecApp.setWindowTitle(_translate("FaceRecApp", "Face Recognition"))
        self.groupBox.setTitle(_translate("FaceRecApp", "Controls"))
        self.startButton.setText(_translate("FaceRecApp", "Start"))
        self.pauseButton.setText(_translate("FaceRecApp", "Pause"))
        self.stopButton.setText(_translate("FaceRecApp", "Stop"))
        self.label.setText(_translate("FaceRecApp", "Album"))
        self.menuFile.setTitle(_translate("FaceRecApp", "File"))
        self.menuDevices.setTitle(_translate("FaceRecApp", "Devices"))
        self.menuView.setTitle(_translate("FaceRecApp", "View"))
        self.actionExit.setText(_translate("FaceRecApp", "Exit"))
        self.actionStartCamera.setText(_translate("FaceRecApp", "Start Camera"))
        self.actionStopCamera.setText(_translate("FaceRecApp", "Stop Camera"))
        self.actionRegisterFaces.setText(_translate("FaceRecApp", "Register faces"))
        self.actionViewFaceRegistry.setText(_translate("FaceRecApp", "Face registry"))
        self.actionAddAlbum.setText(_translate("FaceRecApp", "Add album"))
        self.actionDeleteAlbum.setText(_translate("FaceRecApp", "Delete album"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FaceRecApp = QtWidgets.QMainWindow()
    ui = Ui_FaceRecApp()
    ui.setupUi(FaceRecApp)
    FaceRecApp.show()
    sys.exit(app.exec_())
